### ISSUE TITLE
Preliminary milestone clean up

### ISSUE THREAD

**Issue by trin5tensa** [trin5tensa/pigjar#530]
- [x] - Shelve and take temporary backups of: Transaction module calls v1.8.xxx, pigjar.dat.
- [x] - Use origin/master as base for development.
- [x] - Add a full history validation check after every commit. 
- [x] - Rename `FromAccountForm` to `FromAccountTransactionForm`
- [x] - PEP8 `control.py`
- [x] - Delete branch pigjar-524 & origin/pigjar-524
- [x] - Close issues #524 and #527 as ‘won’t fix’ and related to this new issue
- [x] - Delete Transaction module calls v1.7.xxx
